import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer/Footer";
import Headers from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Creimport Image from ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <main>{children}</main>
      </body>
    </html>
  );
}
